# Generated by Django 5.1 on 2025-01-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_config'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
    ]
