# Generated by Django 5.1 on 2025-01-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='target',
            field=models.CharField(choices=[('ضابط', 'ضابط'), ('ضابط صف', 'ضابط صف'), ('جندي', 'جندي')], default='ضابط', max_length=255),
        ),
    ]
