# Generated by Django 5.1 on 2025-01-15 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('diagnosis', models.TextField(verbose_name='التشخيص')),
                ('hospital', models.CharField(max_length=255, verbose_name='المستشفي')),
                ('recommendation', models.TextField(verbose_name='التوصية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_situations', to='userData.userinfo', verbose_name='الضابط')),
            ],
        ),
    ]
