# Generated by Django 5.1 on 2025-01-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0002_medicalsituation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='classification',
            field=models.CharField(max_length=50, verbose_name='التسكين'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='job_classification',
            field=models.CharField(default='تصنت', max_length=50, verbose_name='الوحدة الفرعية'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='rank',
            field=models.CharField(choices=[('لايكن', 'لايكن'), ('ملازم', 'ملازم'), ('ملازم أول', 'ملازم أول'), ('نقيب', 'نقيب'), ('رائد', 'رائد'), ('مقدم', 'مقدم'), ('مقدم اح', 'مقدم اح'), ('عقيد', 'عقيد'), ('عقيد اح', 'عقيد اح'), ('عميد', 'عميد'), ('عميد اح', 'عميد اح'), ('لواء', 'لواء'), ('لواء اح', 'لواء اح')], default='لايكن', max_length=100, verbose_name='الرتبة'),
        ),
    ]
