months_map = {
    "يناير": 1,
    "فبراير": 2,
    "مارس": 3,
    "أبريل": 4,
    "مايو": 5,
    "يونيو": 6,
    "يوليو": 7,
    "أغسطس": 8,
    "سبتمبر": 9,
    "أكتوبر": 10,
    "نوفمبر": 11,
    "ديسمبر": 12,
}
reversed_month_map = {
    1: "يناير",
    2: "فبراير",
    3: "مارس",
    4: "أبريل",
    5: "مايو",
    6: "يونيو",
    7: "يوليو",
    8: "أغسطس",
    9: "سبتمبر",
    10: "أكتوبر",
    11: "نوفمبر",
    12: "ديسمبر",
}


job_classification_choices = (
    "تصنت",
    "تحديد",
    "امن",
    "حملة",
    "عمليات",
    "إشارة",
    "تدريب",
    "تنظيم وإدارة",
    "تأمين فني",
    "شئون ادارية",
)
classification_choices = (
    "تصنت",
    "تحديد",
    "قيادة",
)
degree_choices = (
    "جندي",
    "عريف",
    "رقيب",
    "رقيب اول",
    "مساعد",
    "مساعد اول",
)
vacation_choices = (
    "الاولي",
    "الثانية",
    "الثالثة",
    "الرابعة",
)


user_info_fields = [
    "militeryNumber",
    "name",
    "classification",
    "job_classification",
    "dgree",
    "study",
    "getInDate",
    "getOutDate",
    "curJob",
    "preJob",
    "birthOfDate",
    "address",
    "status",
    "fullAddress",
    "num_of_brothers_and_sisters",
    "num_of_children",
    "phone_number",
    "dad_or_mom_phone_number",
    "avarol_size",
    "t_shirt_size",
    "shose1_size",
    "shose2_size",
    "mask_size",
    "blood_class",
    "hobby",
    "fasela",
    "saria",
    "vacation",
    "seniority",
    "personal_number",
    "batch",
    "national_id",
    "graduation_date",
    "rank",
    "weapon",
    "religion",
    "current_unit",
    "college_or_institute",
    "email",
    "current_wives",
    "male_children",
    "female_children",
    "marriage_date",
    "previous_marriages",
    "divorce_date",
    "closest_relative",
    "unified_number",
    "is_officer",
    "is_soldier",
]
